/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main1;

import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import koneksi.koneksi;


/**
 *
 * @author USER
 */
public class registerDosen extends javax.swing.JFrame {
int xMouse;
int yMouse;
    /**
     * Creates new form registerDosen
     */
    public registerDosen() {
        initComponents();
        this.setLocationRelativeTo(null);
        tampil_combo_jurusan();
        tampil_combo_mata_kuliah();
    }
public void tampil_combo_jurusan(){
       try{
           
           Statement statement = (Statement) koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("Select * from jurusan");
           
           while(res.next()){
               cmbjurusan.addItem(res.getString("jurusan"));
               
           }
           
           res.last();
           int jumlahdata = res.getRow();
           res.first();
           
       }catch(Exception e){
           
       }
   }
public void tampil_combo_mata_kuliah(){
       try{
           
           Statement statement = (Statement) koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("Select * from mata_kuliah");
           
           while(res.next()){
               cmbmatakuliah.addItem(res.getString("mata_kuliah"));
               
           }
           
           res.last();
           int jumlahdata = res.getRow();
           res.first();
           
       }catch(Exception e){
           
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtpassword = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        txtjabatan = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtnip = new javax.swing.JTextField();
        cmbjurusan = new javax.swing.JComboBox<>();
        cmbjeniskelamin = new javax.swing.JComboBox<>();
        cmbmatakuliah = new javax.swing.JComboBox<>();
        btnsignupdosen = new javax.swing.JLabel();
        btnlogindosen = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        frameDrag = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtpassword.setBackground(new java.awt.Color(236, 236, 236));
        txtpassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpassword.setBorder(null);
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 240, -1));

        txtusername.setBackground(new java.awt.Color(236, 236, 236));
        txtusername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtusername.setBorder(null);
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 240, 30));

        txtjabatan.setBackground(new java.awt.Color(236, 236, 236));
        txtjabatan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtjabatan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtjabatan.setBorder(null);
        getContentPane().add(txtjabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 385, 250, 20));

        txtnama.setBackground(new java.awt.Color(236, 236, 236));
        txtnama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtnama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnama.setBorder(null);
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 250, 20));

        txtnip.setBackground(new java.awt.Color(236, 236, 236));
        txtnip.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtnip.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnip.setBorder(null);
        getContentPane().add(txtnip, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 240, 250, -1));

        cmbjurusan.setBackground(new java.awt.Color(236, 236, 236));
        cmbjurusan.setBorder(null);
        getContentPane().add(cmbjurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 270, 30));

        cmbjeniskelamin.setBackground(new java.awt.Color(236, 236, 236));
        cmbjeniskelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        cmbjeniskelamin.setBorder(null);
        cmbjeniskelamin.setMaximumSize(new java.awt.Dimension(24, 18));
        cmbjeniskelamin.setMinimumSize(new java.awt.Dimension(24, 18));
        cmbjeniskelamin.setPreferredSize(new java.awt.Dimension(24, 18));
        getContentPane().add(cmbjeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 270, 30));

        cmbmatakuliah.setBackground(new java.awt.Color(236, 236, 236));
        cmbmatakuliah.setBorder(null);
        getContentPane().add(cmbmatakuliah, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 270, 30));

        btnsignupdosen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnsignupdosen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsignupdosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsignupdosenMouseClicked(evt);
            }
        });
        getContentPane().add(btnsignupdosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 140, 40));

        btnlogindosen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnlogindosen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogindosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogindosenMouseClicked(evt);
            }
        });
        getContentPane().add(btnlogindosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 160, 40));

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.setText("x");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 40));

        frameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                frameDragMouseDragged(evt);
            }
        });
        frameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                frameDragMousePressed(evt);
            }
        });
        getContentPane().add(frameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Salinan dari REGISTER DOSEN.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsignupdosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsignupdosenMouseClicked
        // TODO add your handling code here:
        if(txtnip.getText().equals("")){
            JOptionPane.showMessageDialog(null,
                "Silahkan refresh terlebih dahulu!");
        }
        else{
            String id_dosen =txtid.getText();
        String nip =txtnip.getText();
        String nama =txtnama.getText();
        String jabatan = txtjabatan.getText();
        String jenis_kelamin = (String) cmbjeniskelamin.getSelectedItem();
        String jurusan = (String) cmbjurusan.getSelectedItem();
        String mata_kuliah = (String) cmbmatakuliah.getSelectedItem();
        String username = txtusername.getText();
        String password = txtpassword.getText();

            try{
                Statement statement = (Statement) koneksi.getConnection().createStatement();
                statement.executeUpdate("insert into dosen VALUES (null, '" + nip + "','"
                    + nama +"','"+ jabatan +"','"+ jenis_kelamin +"','"+ jurusan +"','"+ mata_kuliah +"','"+ username +"','"+ password +"')");
                statement.close();
                JOptionPane.showMessageDialog(null, "Berhasil Mendaftar");

                
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan: " + e.getMessage());
            }
        }
        tampil_combo_jurusan();
        tampil_combo_mata_kuliah();
    }//GEN-LAST:event_btnsignupdosenMouseClicked

    private void btnlogindosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogindosenMouseClicked
        // TODO add your handling code here:
        loginDosen logDos = new loginDosen();
        logDos.setVisible(true);
        logDos.pack();
        logDos.setLocationRelativeTo(null);
        logDos.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnlogindosenMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void frameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_frameDragMouseDragged

    private void frameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_frameDragMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerDosen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnlogindosen;
    private javax.swing.JLabel btnsignupdosen;
    private javax.swing.JComboBox<String> cmbjeniskelamin;
    private javax.swing.JComboBox<String> cmbjurusan;
    private javax.swing.JComboBox<String> cmbmatakuliah;
    private javax.swing.JLabel frameDrag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtjabatan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnip;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
