/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main2;

import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import main1.loginAdmin;

/**
 *
 * @author USER
 */
public class databaseDosen extends javax.swing.JFrame {
int xMouse;
int yMouse;
    /**
     * Creates new form databaseDosen
     */
    public databaseDosen() {
        initComponents();
        this.setLocationRelativeTo(null);
        refresh();
        txtid.setVisible(false);
        tampil_combo_jurusan();
        tampil_combo_mata_kuliah();
    }
private void ambilData() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("NO");
        tbl.addColumn("ID");
        tbl.addColumn("NIP");
        tbl.addColumn("NAMA");
        tbl.addColumn("JABATAN");
        tbl.addColumn("JENIS KELAMIN");
        tbl.addColumn("JURUSAN");
        tbl.addColumn("MATA KULIAH");
        tbl.addColumn("USERNAME");
        tbl.addColumn("PASSWORD");
        table_dosen.setModel(tbl);
        try{
            Statement statement = (Statement) koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("Select * from dosen");
            int index = 1;
            while (res.next())
            {
                tbl.addRow(new Object []{
                    index,
                    res.getString("id_dosen"),
                    res.getString("nip"),
                    res.getString("nama"),
                    res.getString("jabatan"),
                    res.getString("jenis_kelamin"),
                    res.getString("jurusan"),
                    res.getString("mata_kuliah"),
                    res.getString("username"),
                    res.getString("password"),
                });
                table_dosen.setModel(tbl);
                index++;
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Gagal Mengambil Data: " + e.getMessage());
        }
    }
    
    private void refresh()
    {
        txtid.setText("");
        txtnip.setText("");
        txtnama.setText("");
        txtjabatan.setText("");
        cmbjeniskelamin.setSelectedItem("");
        cmbjurusan.setSelectedItem("");
        txtpassword.setText("");
        cmbmatakuliah.setSelectedItem("");
        txtusername.setText("");
        txtnip.requestFocus();
        
        ambilData();
    }
    public void tampil_combo_jurusan(){
       try{
           
           Statement statement = (Statement) koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("Select * from jurusan");
           
           while(res.next()){
               cmbjurusan.addItem(res.getString("jurusan"));
               
           }
           
           res.last();
           int jumlahdata = res.getRow();
           res.first();
           
       }catch(Exception e){
           
       }
   }
    public void tampil_combo_mata_kuliah(){
       try{
           
           Statement statement = (Statement) koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("Select * from mata_kuliah");
           
           while(res.next()){
               cmbmatakuliah.addItem(res.getString("mata_kuliah"));
               
           }
           
           res.last();
           int jumlahdata = res.getRow();
           res.first();
           
       }catch(Exception e){
           
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        btnCreate = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JLabel();
        btnlogout = new javax.swing.JLabel();
        btnDashboardAdminMenu = new javax.swing.JLabel();
        btnDashboardPerkuliahanMenu = new javax.swing.JLabel();
        btnDashboardDosenMenu = new javax.swing.JLabel();
        btnDashboardMahasiswaMenu = new javax.swing.JLabel();
        btnDashboardHome = new javax.swing.JLabel();
        txtnip = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtjabatan = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        cmbjurusan = new javax.swing.JComboBox<>();
        cmbmatakuliah = new javax.swing.JComboBox<>();
        cmbjeniskelamin = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_dosen = new javax.swing.JTable();
        frameDrag = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.setText("x");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 40));

        btnCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateMouseClicked(evt);
            }
        });
        getContentPane().add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 70, 20));

        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 70, 20));

        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 70, 20));

        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 70, 30));

        btnlogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogoutMouseClicked(evt);
            }
        });
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 284, 150, 30));

        btnDashboardAdminMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDashboardAdminMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboardAdminMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardAdminMenuMouseClicked(evt);
            }
        });
        getContentPane().add(btnDashboardAdminMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 244, 150, 30));

        btnDashboardPerkuliahanMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDashboardPerkuliahanMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboardPerkuliahanMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardPerkuliahanMenuMouseClicked(evt);
            }
        });
        getContentPane().add(btnDashboardPerkuliahanMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 210, 150, 30));

        btnDashboardDosenMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDashboardDosenMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboardDosenMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardDosenMenuMouseClicked(evt);
            }
        });
        getContentPane().add(btnDashboardDosenMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 150, 30));

        btnDashboardMahasiswaMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDashboardMahasiswaMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboardMahasiswaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMahasiswaMenuMouseClicked(evt);
            }
        });
        getContentPane().add(btnDashboardMahasiswaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 134, 150, 30));

        btnDashboardHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboardHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardHomeMouseClicked(evt);
            }
        });
        getContentPane().add(btnDashboardHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, 30));

        txtnip.setBackground(new java.awt.Color(166, 166, 166));
        txtnip.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtnip.setForeground(new java.awt.Color(255, 255, 255));
        txtnip.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnip.setBorder(null);
        getContentPane().add(txtnip, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 220, 20));

        txtnama.setBackground(new java.awt.Color(166, 166, 166));
        txtnama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtnama.setForeground(new java.awt.Color(255, 255, 255));
        txtnama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnama.setBorder(null);
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 220, 30));

        txtjabatan.setBackground(new java.awt.Color(166, 166, 166));
        txtjabatan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtjabatan.setForeground(new java.awt.Color(255, 255, 255));
        txtjabatan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtjabatan.setBorder(null);
        getContentPane().add(txtjabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 220, 20));

        txtusername.setBackground(new java.awt.Color(166, 166, 166));
        txtusername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtusername.setBorder(null);
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 230, 20));

        txtpassword.setBackground(new java.awt.Color(166, 166, 166));
        txtpassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpassword.setBorder(null);
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 535, 230, 20));

        cmbjurusan.setBackground(new java.awt.Color(236, 236, 236));
        cmbjurusan.setBorder(null);
        getContentPane().add(cmbjurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 260, 30));

        cmbmatakuliah.setBackground(new java.awt.Color(236, 236, 236));
        cmbmatakuliah.setBorder(null);
        getContentPane().add(cmbmatakuliah, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 260, 30));

        cmbjeniskelamin.setBackground(new java.awt.Color(236, 236, 236));
        cmbjeniskelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        cmbjeniskelamin.setBorder(null);
        cmbjeniskelamin.setMaximumSize(new java.awt.Dimension(24, 18));
        cmbjeniskelamin.setMinimumSize(new java.awt.Dimension(24, 18));
        cmbjeniskelamin.setPreferredSize(new java.awt.Dimension(24, 18));
        getContentPane().add(cmbjeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 240, 30));

        table_dosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_dosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_dosenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_dosen);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 480, 200));

        frameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                frameDragMouseDragged(evt);
            }
        });
        frameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                frameDragMousePressed(evt);
            }
        });
        getContentPane().add(frameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/DATABASE DOSEN ADMIN.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 50, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_dosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_dosenMouseClicked
        // TODO add your handling code here:
        int i = table_dosen.getSelectedRow();
        if (i == -1){
            return;
        }
        String id_dosen = (String) table_dosen.getValueAt(i, 1);
        txtid.setText(id_dosen);
        String nip = (String) table_dosen.getValueAt(i, 2);
        txtnip.setText(nip);
        String nama = (String) table_dosen.getValueAt(i, 3);
        txtnama.setText(nama);
        String jabatan = (String) table_dosen.getValueAt(i, 4);
        txtjabatan.setText(jabatan);
        String jenis_kelamin = (String) table_dosen.getValueAt(i, 5);
        cmbjeniskelamin.setSelectedItem(jenis_kelamin);
        String jurusan = (String) table_dosen.getValueAt(i, 6);
        cmbjurusan.setSelectedItem(jurusan);
        String id_mata_kuliah = (String) table_dosen.getValueAt(i, 7);
        cmbmatakuliah.setSelectedItem(id_mata_kuliah);
        String username = (String) table_dosen.getValueAt(i, 8);
        txtusername.setText(username);
        String password = (String) table_dosen.getValueAt(i, 9);
        txtpassword.setText(password);
    }//GEN-LAST:event_table_dosenMouseClicked

    private void btnlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseClicked
        // TODO add your handling code here:
        loginAdmin Admin = new loginAdmin();
        Admin.setVisible(true);
        Admin.pack();
        Admin.setLocationRelativeTo(null);
        Admin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnlogoutMouseClicked

    private void btnDashboardAdminMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardAdminMenuMouseClicked
        // TODO add your handling code here:
        dashboardAdminMenu dshAdmin = new dashboardAdminMenu();
        dshAdmin.setVisible(true);
        dshAdmin.pack();
        dshAdmin.setLocationRelativeTo(null);
        dshAdmin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnDashboardAdminMenuMouseClicked

    private void btnDashboardPerkuliahanMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardPerkuliahanMenuMouseClicked
        // TODO add your handling code here:
        dashboardPerkuliahanMenu dshPerkuliahan = new dashboardPerkuliahanMenu();
        dshPerkuliahan.setVisible(true);
        dshPerkuliahan.pack();
        dshPerkuliahan.setLocationRelativeTo(null);
        dshPerkuliahan.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnDashboardPerkuliahanMenuMouseClicked

    private void btnDashboardDosenMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardDosenMenuMouseClicked
        // TODO add your handling code here:
        dashboardDosenMenu dshDosen = new dashboardDosenMenu();
        dshDosen.setVisible(true);
        dshDosen.pack();
        dshDosen.setLocationRelativeTo(null);
        dshDosen.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnDashboardDosenMenuMouseClicked

    private void btnDashboardMahasiswaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMahasiswaMenuMouseClicked
        // TODO add your handling code here:
        dashboardMahasiswaMenu dshMahasiswa = new dashboardMahasiswaMenu();
        dshMahasiswa.setVisible(true);
        dshMahasiswa.pack();
        dshMahasiswa.setLocationRelativeTo(null);
        dshMahasiswa.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnDashboardMahasiswaMenuMouseClicked

    private void btnDashboardHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardHomeMouseClicked
        // TODO add your handling code here:
        dashboardAdmin dshAdmin = new dashboardAdmin();
        dshAdmin.setVisible(true);
        dshAdmin.pack();
        dshAdmin.setLocationRelativeTo(null);
        dshAdmin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnDashboardHomeMouseClicked

    private void btnCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseClicked
        // TODO add your handling code here:
        if(txtnip.getText().equals("")){
            JOptionPane.showMessageDialog(null,
                "Silahkan refresh terlebih dahulu!");
        }
        else{
            String id_dosen = txtid.getText();
            String nip = txtnip.getText();
            String nama = txtnama.getText();
            String jabatan = txtjabatan.getText();
            String jenis_kelamin = (String) cmbjeniskelamin.getSelectedItem();
            String jurusan = (String) cmbjurusan.getSelectedItem();
            String id_mata_kuliah = (String) cmbmatakuliah.getSelectedItem();
            String username = txtusername.getText();
            String password = txtpassword.getText();

            try{
                Statement statement = (Statement) koneksi.getConnection().createStatement();
                statement.executeUpdate("insert into dosen VALUES (null, '" + nip + "','"
                    + nama +"','"+ jabatan +"','"+ jenis_kelamin +"','"+ jurusan +"','"+ id_mata_kuliah +"','"+ username +"','"+ password +"')");
                statement.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil disimpan");

                refresh();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan: " + e.getMessage());
            }
        }
        tampil_combo_jurusan();
        tampil_combo_mata_kuliah();
    }//GEN-LAST:event_btnCreateMouseClicked

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_btnRefreshMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        if(txtid.getText().equals("")){
            JOptionPane.showMessageDialog(null,
                "Silahkan pilih terlebih dahulu data yang akan dihapus!");
        }
        else{
            String id = txtid.getText();

            try{
                Statement statement = (Statement) koneksi.getConnection().createStatement();
                statement.executeUpdate("delete from dosen where id_dosen = '" + id + "'");
                JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus");

                refresh();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Data Gagal di Hapus: " + e.getMessage());
            }
        }
        tampil_combo_jurusan();
        tampil_combo_mata_kuliah();
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        if(txtid.getText().equals("")){
            JOptionPane.showMessageDialog(null,
                "Silahkan pilih terlebih dahulu data yang akan  diupdate!");
        }
        else{
            String id_dosen = txtid.getText();
            String nip = txtnip.getText();
            String nama = txtnama.getText();
            String jabatan = txtjabatan.getText();
            String jenis_kelamin = (String) cmbjeniskelamin.getSelectedItem();
            String jurusan = (String) cmbjurusan.getSelectedItem();
            String id_mata_kuliah = (String) cmbmatakuliah.getSelectedItem();
            String username = txtusername.getText();
            String password = txtpassword.getText();
            
            try{
                Statement statement = (Statement) koneksi.getConnection().createStatement();
                statement.executeUpdate("update dosen SET nip='"+nip+"'," + "nama='"+nama+"',"
                    + "jabatan='"+jabatan+"',"
                    +"jenis_kelamin='"+jenis_kelamin+"',"
                    + "jurusan='"+jurusan+"',"
                    + "mata_kuliah='"+id_mata_kuliah+"'," 
                    + "username='"+username+"',"       
                    + "password='"+password+"' " + "WHERE id_dosen = '"+id_dosen+"'");
                statement.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil diubah");

                refresh();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Data Gagal diubah: " + e.getMessage());
            }
        }
        tampil_combo_jurusan();
        tampil_combo_mata_kuliah();
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void frameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_frameDragMouseDragged

    private void frameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_frameDragMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(databaseDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(databaseDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(databaseDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(databaseDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new databaseDosen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCreate;
    private javax.swing.JLabel btnDashboardAdminMenu;
    private javax.swing.JLabel btnDashboardDosenMenu;
    private javax.swing.JLabel btnDashboardHome;
    private javax.swing.JLabel btnDashboardMahasiswaMenu;
    private javax.swing.JLabel btnDashboardPerkuliahanMenu;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel btnRefresh;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.JLabel btnlogout;
    private javax.swing.JComboBox<String> cmbjeniskelamin;
    private javax.swing.JComboBox<String> cmbjurusan;
    private javax.swing.JComboBox<String> cmbmatakuliah;
    private javax.swing.JLabel frameDrag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_dosen;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtjabatan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnip;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
