/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main3;

import javax.swing.JFrame;
import main1.loginDosen;

/**
 *
 * @author USER
 */
public class dashboardDosen extends javax.swing.JFrame {
int xMouse;
int yMouse;
    /**
     * Creates new form dashboardDosen
     */
    public dashboardDosen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        btndashboardDosen = new javax.swing.JLabel();
        btnPresensiMenu = new javax.swing.JLabel();
        btnPresensi = new javax.swing.JLabel();
        btnMulaiAbsen = new javax.swing.JLabel();
        btnlogout = new javax.swing.JLabel();
        frameDrag = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.setText("x");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 40));

        btndashboardDosen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btndashboardDosen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndashboardDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndashboardDosenMouseClicked(evt);
            }
        });
        getContentPane().add(btndashboardDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, 20));

        btnPresensiMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPresensiMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPresensiMenu.setText("DASHBOARD PRESENSI");
        btnPresensiMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPresensiMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPresensiMenuMouseClicked(evt);
            }
        });
        getContentPane().add(btnPresensiMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 240, 90));

        btnPresensi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPresensi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPresensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPresensiMouseClicked(evt);
            }
        });
        getContentPane().add(btnPresensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 150, 20));

        btnMulaiAbsen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMulaiAbsen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMulaiAbsen.setText("MULAI ABSEN");
        btnMulaiAbsen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMulaiAbsen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMulaiAbsenMouseClicked(evt);
            }
        });
        getContentPane().add(btnMulaiAbsen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 230, 90));

        btnlogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogoutMouseClicked(evt);
            }
        });
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 150, 30));

        frameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                frameDragMouseDragged(evt);
            }
        });
        frameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                frameDragMousePressed(evt);
            }
        });
        getContentPane().add(frameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/DASHBOARD DOSEN .png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseClicked
        // TODO add your handling code here:
        loginDosen Dosen = new loginDosen();
        Dosen.setVisible(true);
        Dosen.pack();
        Dosen.setLocationRelativeTo(null);
        Dosen.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnlogoutMouseClicked

    private void btnPresensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPresensiMouseClicked
        // TODO add your handling code here:
        dashboardPresensi Presensi = new dashboardPresensi();
        Presensi.setVisible(true);
        Presensi.pack();
        Presensi.setLocationRelativeTo(null);
        Presensi.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnPresensiMouseClicked

    private void btndashboardDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashboardDosenMouseClicked
        // TODO add your handling code here:
        dashboardDosen Dosen = new dashboardDosen();
        Dosen.setVisible(true);
        Dosen.pack();
        Dosen.setLocationRelativeTo(null);
        Dosen.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btndashboardDosenMouseClicked

    private void btnPresensiMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPresensiMenuMouseClicked
        // TODO add your handling code here:
        dashboardPresensi Presensi = new dashboardPresensi();
        Presensi.setVisible(true);
        Presensi.pack();
        Presensi.setLocationRelativeTo(null);
        Presensi.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnPresensiMenuMouseClicked

    private void btnMulaiAbsenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMulaiAbsenMouseClicked
        // TODO add your handling code here:
        mulaiAbsen mulaiAbsen = new mulaiAbsen();
        mulaiAbsen.setVisible(true);
        mulaiAbsen.pack();
        mulaiAbsen.setLocationRelativeTo(null);
        mulaiAbsen.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnMulaiAbsenMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void frameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_frameDragMouseDragged

    private void frameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_frameDragMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardDosen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnMulaiAbsen;
    private javax.swing.JLabel btnPresensi;
    private javax.swing.JLabel btnPresensiMenu;
    private javax.swing.JLabel btndashboardDosen;
    private javax.swing.JLabel btnlogout;
    private javax.swing.JLabel frameDrag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    // End of variables declaration//GEN-END:variables
}
